version: '3.7'

services:
  postgreSQL:
    image: postgres
    ports:
      - "5434:5432"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5